name: Build EXE on Windows

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build exe
      run: pyinstaller seathr.py --onefile

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: seathr-exe
        path: dist/seathr.exe
